template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "vlax1238"
__REPO__ = "lang-rmy"
__UND2C__ = "rmy"
__UNDEFINED__ = "Vlax Romani"
__UND__ = "rmy"
