template = "https://github.com/giellalt/template-lang-und"
rev_id = 317
template_sha = "3d0bcfa8020a96bc946192565f7e92213470a110"

[replacements]
__GLOTTOLOG_ID__ = "vlax1238"
__REPO__ = "lang-rmy"
__UND2C__ = "rmy"
__UNDEFINED__ = "Vlax Romani"
__UND__ = "rmy"
